[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["Johannes Wågen <johannes@wagen.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
